[workspace]
members = [
    "proxy",
    "meme",
    "swap",
    "liquidity-rfq",
    "abi",
]
resolver = "2"

[workspace.dependencies]
async-graphql = { version = "=7.0.2", default-features = false }
# linera-sdk = { version = "0.14.0", git = "https://github.com/linera-io/linera-protocol.git" }
# linera-views = { version = "0.14.0", git = "https://github.com/linera-io/linera-protocol.git" }
linera-sdk = { version = "0.14.0", git = "https://github.com/kikakkz/linera-protocol.git" }
linera-views = { version = "0.14.0", git = "https://github.com/kikakkz/linera-protocol.git" }
futures = { version = "0.3 "}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1.40", features = ["rt", "sync"] }
assert_matches = "1.5.0"
thiserror = "^1.0.65"
log = "0.4.21"
tracing = { version = "0.1.40", features = ["release_max_level_debug"] }

abi = { path = "./abi" }
meme = { path = "./meme" }
proxy = { path = "./proxy" }
swap = { path = "./swap" }
liquidity-rfq = { path = "./liquidity-rfq" }

[profile.release]
debug = true
lto = true
opt-level = 'z'
strip = 'debuginfo'
