[workspace]
members = [
    "proxy",
    "meme",
    "swap",
    "liquidity-rfq",
    "pool",
    "abi",
]
resolver = "2"

[workspace.dependencies]
async-graphql = { version = "=7.0.2", default-features = false }
linera-sdk = { version = "0.14.0", git = "https://github.com/linera-io/linera-protocol.git", rev = "ab44d8a6c" }
linera-views = { version = "0.14.0", git = "https://github.com/linera-io/linera-protocol.git", rev = "ab44d8a6c" }
futures = { version = "0.3 "}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1.40", features = ["rt", "sync"] }
assert_matches = "1.5.0"
thiserror = "^1.0.65"
log = "0.4.21"
env_logger = "0.9"
primitive-types = { version = "^0.13.1", features = ["serde"] }
rust_decimal = "1.36"

abi = { path = "./abi" }
meme = { path = "./meme" }
proxy = { path = "./proxy" }
swap = { path = "./swap" }
liquidity-rfq = { path = "./liquidity-rfq" }
pool = { path = "./pool" }

[profile.release]
debug = true
lto = true
opt-level = 'z'
strip = 'debuginfo'

