[workspace]
members = [
    "proxy",
]
resolver = "2"

[workspace.dependencies]
async-graphql = { version = "=7.0.2", default-features = false }
linera-sdk = { version = "0.14.0", git = "https://github.com/linera-io/linera-protocol.git", features = ["test", "wasmer"] }
futures = { version = "0.3 "}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1.40", features = ["rt", "sync"] }

[profile.release]
debug = true
lto = true
opt-level = 'z'
strip = 'debuginfo'
