services:
  maker-wallet:
    image: "respeer/linera-respeer"
    container_name: maker-wallet
    ports:
      - "40082:8080"
    command: [ "./wallet-entrypoint.sh" ]
    volumes:
      - ../wallet/maker/0:/wallet
